# Claves únicas provistas por SonarCloud
sonar.projectKey=ecarrillo16_creatorhub
sonar.organization=ecarrillo16

# Información del proyecto
sonar.projectName=creatorHub
sonar.projectVersion=1.0

# Rutas del código fuente a analizar (apuntando a tu backend de NestJS)
sonar.sources=apps/backend/src
sonar.tests=apps/backend/src
sonar.test.inclusions=apps/backend/src/**/*.spec.ts,apps/backend/src/**/*.test.ts

# Configuración del entorno de TypeScript
sonar.language=ts
sonar.typescript.tsconfigPath=apps/backend/tsconfig.json

# Exclusiones comunes para no ensuciar tus métricas
sonar.exclusions=**/node_modules/**, **/dist/**,apps/backend/prisma/**
